ALTER TYPE "PaymentProviderName" ADD VALUE IF NOT EXISTS 'TRIBOPAY';
ALTER TYPE "PaymentProviderName" ADD VALUE IF NOT EXISTS 'MANGOFY';
ALTER TYPE "PaymentProviderName" ADD VALUE IF NOT EXISTS 'SIGILOPAY';
ALTER TYPE "PaymentProviderName" ADD VALUE IF NOT EXISTS 'LYTRONPAY';
ALTER TYPE "PaymentProviderName" ADD VALUE IF NOT EXISTS 'ALLOWPAYMENTS';

ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'TRIBOPAY';
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'MANGOFY';
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'SIGILOPAY';
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'LYTRONPAY';
ALTER TYPE "WebhookProvider" ADD VALUE IF NOT EXISTS 'ALLOWPAYMENTS';
